site_name: DATAIDEA DOCS
site_url: https://docs.dataidea.org/
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.footer
    - navigation.top
    # - navigation.tabs
    - navigation.expand
    # - navigation.sections
    - navigation.indexes
    - content.code.copy

  font:
    text: DM Sans
    code: DM Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
extra_css:
  - styles/custom.css
extra:
  generator: false
#
