site_name: DATAIDEA DOCS
site_url: https://docs.dataidea.org/
theme:
  name: material
  features:
    - navigation.footer
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: "#008374"
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: "#008374"
      accent: deep orange
#
