site_name: DATAIDEA DOCS
site_url: https://docs.dataidea.org/
site_author: Juma Shafara
site_description: DATAIDEA Documentation
site_author_email: jumashafara@gmail.com
site_author_github: https://github.com/jumashafara

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  favicon: assets/logo.png
  logo: assets/logo.png
  name: material
  # customization
  custom_dir: overrides

  # features
  features:
    # header
    - header.autohide

    # navigation
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.expand
    # - navigation.sections
    - navigation.indexes
    - content.code.copy

    # announcements
    - announce.dismiss

  # fonts
  font:
    text: DM Sans
    code: DM Mono

  # palette
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom

# extra
extra_css:
  - styles/custom.css
extra:
  generator: false
  homepage: https://www.dataidea.org/
#
